---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAHIJjgYAQdeKlp0AgpXtf1waISYHrgLSqtmp5yLmO6guMdafQx1OFi9JPAf2mfBkjpS1BilGKbBJQMtqOapxs6GHQHSwwQjU6o2lu6/NDFs4LWjtWkY19W8LhOPO9JA1WK/GTWXAm1CHB9Nojvf8mqOdBGMK98UkLO9pdSvW5vE2CgogS/a5/ZnGzf9KjogcXsYX5lHHn56WbJITEQBBDgJNRdHFkLcFGWnEhkojsunwf1eZMxwLHHvF7q5XQBvo4c6ZDBbC/2pzXs1wg3HML39x5I3QhA0TCZcsZqh5mG+o/ALhQcEjG6qWJtqgdKKfEKW1RapsmOgzuMr4O78VeZzOhBExl2wFuQ+2tUeG+HAg9Pj3NSgMPdqgZzXWde5RLdMY76BQgBft/5d3bpbordfmZaba1AKzuhbnVN/rmUIbXW+gmIwoB5cJx/cv5ZnCvA4VU71lQLlRwLq0zAcbRTheEFjT9Ae7fixF8eMZqLlMGQ1kBg/v/AN6o/yHtd7EFzMaTbcSjhwUUxix63lKHN7Ff7j8Vc/WcXqDoR8/DoJgknGoHgjPcNF5To8dmoy3D62rC341tsmVu6q6gADPVIyDdUWIcXz4nzG78OsKb77cqKlVjOU976PUhiNliP7apHKaIR2FdE+++Wl8krWit+3rLI2uRy4uMDrvRDBRLHK2DSXSl+5jJq7ZfF+q/SC3JToF+q2IuqByee/9C+vhxl
    username: AgBzQRjRKRFIw4PkRSXSsi4SC7qHgjiJlIMPd3ZwYRTkpLRPkW1Ek8OwHaoD/FgdEpWBxkIJu2a4pV2+25BqMVthZdq7bb1h7+6wX9jXzJteudZQbZUd190QIMMdPl1P1KPAYlIzmoi9im2W4gzCqok0gotO2pTOJoLAr4dQ4+pJLPr+6rZqb3vHLffN8qoaSlH0lxpenxBDoQWK6Vz7dWywEBys7GNcunYlDLi8NLiC7Uj58OIiFnXU1Wj/TT5M+KEpj6wWZLyQSYFL7Z2g8L4VLBmGfOnK6pfbn8XaEt1N+V9xFvouHxhS5r8mSIjcFPMEkwwznwOHQggyBky9/KRMpDSSQ70uFWBldsNXhK4VkW0Gz1H+IwbZv9X+egywq4yyji6Zcv3JqQh57slS/Y1Pa/NoFSZDnE+fT6MQ8UYnbl0YedOGaAx2S21BEFWKRqyoCsgcOJgW3LmNSVtabTYRuFu0kW6MpdUIZkyzN7SX5ehccZWLQXLdF+ioasAMuf8rQmWb1x6go0Sj1y00a1DalpjrmIbwrKezdL0yn2x3FixCzTSsbjgh74SFzGZxGo+kxAYQmteZwnCZN+OxO+vAPs3pCIDArHq9trlqILGLHPoE2VdEFDnW+dTDs+IhOzXIGaXRXg1X1CQ+E0/GwhM+3BAywABxuq9fSlFbdPZpQb5N9v7Rj86K6Z9lOAyYaNmYQBaeuA==
  template:
    metadata:
      creationTimestamp: null
      name: db-credentials
      namespace: default
    type: Opaque
