apiVersion: v1
kind: Service
metadata:
  name: devops-final-service
spec:
  type: NodePort
  selector:
    app: devops-final-app
  ports:
    - port: 3000           # Cluster-wide service port
      targetPort: 3000     # Must match the Node.js app port
      nodePort: 30080      # Exposed port on your node (external access)