apiVersion: v1
kind: Service
metadata:
  name: devops-final-service
spec:
  type: NodePort
  selector:
    app: devops-final-app
  ports:
    - port: 3000          # Service port (matches app port)
      targetPort: 3000    # Container port
      nodePort: 30080     # NodePort to access app externally
