apiVersion: v1
kind: Service
metadata:
  name: devops-final-service
spec:
  type: NodePort         # Change to LoadBalancer if on cloud (EKS/GKE/AKS)
  selector:
    app: devops-final-app
  ports:
    - name: http
      port: 80
      targetPort: 3000   # <-- Forward traffic to your app port
      nodePort: 30080    # <-- Optional, only for NodePort access
