name: DevSecOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  security-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install tfsec for Terraform scanning
    - name: Run tfsec (Terraform Security Scan)
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ashminita28/devops-final-project:latest .

    # Step 4: Trivy scan on the built image
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.11.0
      with:
        image-ref: ashminita28/devops-final-project:latest
        format: table
        severity: HIGH,CRITICAL

    # Step 5: Login to DockerHub (replace with your credentials)
    - name: Docker Login
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}


    # Step 6: Push Docker image
    - name: Push Docker image
      run: |
        docker push ashminita28/devops-final-project:latest

    # Step 7: Setup kubectl
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.27.1

    # Step 8: Configure kubeconfig (replace with your cluster secret)
    - name: Set Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_FILE }}" > ~/.kube/config

    # Step 9: Apply Sealed Secrets
    - name: Apply Sealed Secrets
      run: |
        kubectl apply -f k8s/sealed-secret.yaml

    # Step 10: Deploy to Kubernetes (replace with your deployment YAML path)
    - name: Deploy Workloads
      run: |
        kubectl apply -f k8s/
